### ISSUE TITLE
关于在mxnet gluon中使用预训练的word2vec的另一种方法

### ISSUE THREAD

**Issue by HikaruSama233** [NonvolatileMemory/MXNET-SMN#2]
先用```contrib.text.embedding.CustomEmbedding('word2vecfile.txt')```把预存在本地的word2vec的txt文件Load进去成为```inputEmbedding```，
再用```encoder.embedding.initialize(init.Constant(inputEmbedding.idx_to_vec))``` 进行embedding层的初始化
```
class Encoder(nn.Block):
    def __init__(self, num_inputs, embed_size, ...):
        super(Encoder, self).__init__(**kwargs)
        self.embedding = nn.Embedding(num_inputs, embed_size)
        ...
    def forward(self, ...):
        ...
encoder = Encoder(...)
```
这样就可以用```.embedding```，不用专门去看embedding层的名称。

因为不想注册知乎就跑过来提issue了……可能不是很有必要orz

**Comment by NonvolatileMemory** [comment]
嗯，不过contrib的时候还没有这些api

**Comment by NonvolatileMemory** [comment]
如果你想为本项目做贡献的话欢迎pr
本issue已经被关闭
